namespace: default

image:
  name: img234/fastapi-img-process-manager
  tag: 0.1.1-beta

port: 21101

appId: "fastapi-img-process-manager-001"

replicaCount: 1

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

serviceType: LoadBalancer
