apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-img-process-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/parkyoungjin-888/k8s-app.git
    targetRevision: main
    path: manifests/fastapi-img-process-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
