apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image }}:{{ .tag }}"
          ports:
            - containerPort: {{ .port }}
          env:
            - name: CONFIG_HOST
              value: "{{ $.Values.configServer.host }}"
            - name: CONFIG_PORT
              value: "{{ $.Values.configServer.port }}"
            - name: APP_ID
              value: "{{ .appId }}"
          resources: {{- toYaml $.Values.resources | nindent 12 }}
      restartPolicy: Always
