services:
  - name: fastapi-img-process-manager
    image: img234/fastapi-collection-manager
    tag: "0.1.0"
    port: 21101
    appId: "fastapi-img-process-manager-001"

  - name: grpc-img-process-manager
    image: img234/grpc-collection-manager
    tag: "0.1.2"
    port: 21002
    appId: "grpc-img-process-manager-001"

configServer:
  host: grpc-config-server
  port: 21001

replicaCount: 1

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

serviceType: LoadBalancer
